# Generated by Django 5.2 on 2025-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_myusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='email',
            field=models.EmailField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myusers',
            name='username',
            field=models.EmailField(),
            preserve_default=False,
        ),
    ]
