# Generated by Django 5.2 on 2025-04-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_myusers_email_myusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='username',
        ),
    ]
