# Generated by Django 5.2 on 2025-05-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_dislike_count_remove_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Dislike', 'verbose_name_plural': 'Dislike'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Like'},
        ),
    ]
