# Generated by Django 5.2 on 2025-04-29 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_myusers_email_remove_myusers_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myusers',
            new_name='Post',
        ),
    ]
