# Generated by Django 5.2 on 2025-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentdislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='dislike',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
