# Generated by Django 5.2 on 2025-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commentdislike_session_key_commentlike_session_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
