# Generated by Django 5.2 on 2025-05-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_dislike_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Dislike', 'verbose_name_plural': 'Dislike'},
        ),
    ]
